# Generated by Django 2.2.3 on 2019-07-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('clima', models.CharField(max_length=20)),
                ('terreno', models.CharField(max_length=20)),
            ],
        ),
    ]
